routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomAuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
| in laravel Route there is two parameters url and call back 
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/

Route::get('/', 'App\Http\Controllers\PresentationController@index');
Route::get('/about', 'App\Http\Controllers\PresentationController@about');
Route::get('/LaravelQuestions', 'App\Http\Controllers\PresentationController@LaravelQuestions');
Route::get('/LaravelDatabaseSeeding', 'App\Http\Controllers\PresentationController@LaravelDatabaseSeeding');
Route::get('/LaravelTinker', 'App\Http\Controllers\PresentationController@LaravelTinker');
Route::get('/Laraveljson', 'App\Http\Controllers\PresentationController@Laraveljson');

Route::get('/Laraveljson_import_test', 'App\Http\Controllers\jsonImportController@index');

Route::get('/blog', 'App\Http\Controllers\BlogController@index');

Route::get('/hello', function () {
    return "This is a simple Route returning hello message";
});

Route::get('users/{id}', function ($id) {
    return "Your id id $id";
});

/*
Route::get('/usershome', 'App\Http\Controllers\usersController@index')->name('usershome');
Route::get('/usercreate', 'App\Http\Controllers\usersController@create')->name('usercreate');
Route::post('/usercreate', 'App\Http\Controllers\usersController@store')->name('store');
*/
Route::resource('users', 'App\Http\Controllers\usersController');
Route::get('users', [App\Http\Controllers\usersController::class, 'getData']);

//Route::get('/companyhome', 'App\Http\Controllers\companyController@index')->name('companyhome');
//Route::resource('companyhome', 'App\Http\Controllers\companyController');
//Route::resource('customers','CustomerController');
//Route::resource('companyhome','companyController');
Route::resource('company', 'App\Http\Controllers\companyController');
Route::get('company', [App\Http\Controllers\companyController::class, 'getData']);

//Route::get('welcome', [CustomAuthController::class, 'welcome']); 
Route::get('login', [CustomAuthController::class, 'index'])->name('login');
Route::post('custom-login', [CustomAuthController::class, 'customLogin'])->name('login.custom'); 
Route::get('registration', [CustomAuthController::class, 'registration'])->name('register-user');
Route::post('custom-registration', [CustomAuthController::class, 'customRegistration'])->name('register.custom'); 
Route::get('signout', [CustomAuthController::class, 'signOut'])->name('signout');

Route::get('welcome', function () {
    return view('welcome');
});

app/Models/user.php
<?php
// App\Models\user.php
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;


class user extends Authenticatable
{
    protected $table = 'users';
    use Notifiable;
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public $fillable = [
        'first_name',
        'last_name',
        'email',     
        'phone',
        'password',
    ];    

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role(){
        return $this->belongsTo('App\Models\Role');
    }

}

app/Http/Controllers/usersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\user;  // use user model
use DataTables;
use Illuminate\Support\Facades\DB;
Use Redirect;
use Illuminate\Support\Facades\Auth;
use Session;

class usersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = user::all();
        return view('users.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('createuser');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $user = new user;
        $user -> first_name = $request -> input('first_name');
        $user -> last_name = $request -> input('last_name');
        $user -> email = $request -> input('email');
        $user -> phone = $request -> input('phone');
        $user -> role_id = $request -> input('role_id');
        $user -> save();
        return redirect(route('usershome')) -> with('successMsg','User sucessfull added');

    }



    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = user::find($id);
        return view('users.edit', compact('user'));        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'first_name'=>'required',
            'email'=>'required'
        ]);
        /*
            'first_name' => 'Admin',
            'last_name' => 'Admin',
            'email' => 'Admin@admin.com',
            'phone' => '0022115511',
            'role_id' => 1,
            'password' => bcrypt('root'),

        */

        $user = user::find($id);
        $user->first_name =  $request->first_name;
        $user->last_name =  $request->last_name;
        $user->email = $request->get('email');
        $user->phone = $request->get('phone');
        if (!empty($request->password)) {
            $user->password = bcrypt($request->password); //  update password only if modified
            //$user->password = $request->get('password'); //  update password only if modified
            }
        $user->save();
        
        $notification = array(
            'message' => "User (<b>" . $request->get('first_name') . "</b>) updated!",
            'alert-type' => 'success'
        );

        return redirect("users")->with($notification);    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    public function getData()
    {
    if(Auth::check()){
        $users = user::paginate(5);
        return view('users.index', compact('users'));
    }

    $notification = array(
        'message' => "You are not allowed to access users data!",
        'alert-type' => 'alert-success');

    return redirect("welcome")->with($notification);

}

}

resources/views/users/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add a user</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('users.store') }}">
          @csrf
          <div class="form-group">    
              <label for="first_name">First Name:</label>
              <input type="text" class="form-control" name="first_name"/>
          </div>

          <div class="form-group">
              <label for="last_name">Last Name:</label>
              <input type="text" class="form-control" name="last_name"/>
          </div>

          <div class="form-group">
              <label for="email">Email:</label>
              <input type="text" class="form-control" name="email"/>
          </div>
          <div class="form-group">
              <label for="city">City:</label>
              <input type="text" class="form-control" name="city"/>
          </div>
          <div class="form-group">
              <label for="country">Country:</label>
              <input type="text" class="form-control" name="country"/>
          </div>
          <div class="form-group">
              <label for="job_title">Job Title:</label>
              <input type="text" class="form-control" name="job_title"/>
          </div>                         
          <button type="submit" class="btn btn-primary-outline">Add user</button>
      </form>
  </div>
</div>
</div>

    
@endsection

resources/views/users/edit.blade.php
@extends('layouts.main')

@section('title', 'Users Edit')

@section('content')

<main id="main">

    <!-- ======= company Section ======= -->
    <section id="user" class="user">

      <div class="container" data-aos="fade-up">

        <header class="section-header">
          <h2>Users</h2>
          <p>Listing</p>
        </header>

        <div class="container">
        
        @if (session('message'))
        <div class="alert session('alert-type')">
         {!! session('message') !!}
        </div>
        @endif


<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a user</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('users.update', $user->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="first_name">First Name:</label>
                <input type="text" class="form-control" name="first_name" value="{{ $user->first_name }}" />
            </div>

            <div class="form-group">
                <label for="last_name">Last Name:</label>
                <input type="text" class="form-control" name="last_name" value="{{ $user->last_name }}" />
            </div>

            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" class="form-control" name="email" value="{{ $user->email }}" />
            </div>
            <div class="form-group">
                <label for="phone">Phone:</label>
                <input type="text" class="form-control" name="phone" value="{{ $user->phone }}" />
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" class="form-control" name="password" value="" />
            </div>

            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>

<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.main')

@section('title', 'Users Home')

@section('content')
 
<main id="main">

    <!-- ======= company Section ======= -->
    <section id="user" class="user">

      <div class="container" data-aos="fade-up">

        <header class="section-header">
          <h2>Users</h2>
          <p>Listing</p>
        </header>

        <div class="container">
        
        @if (session('message'))
        <div class="alert session('alert-type')">
         {!! session('message') !!}
        </div>
        @endif

    <a class="btn btn-success" href="javascript:void(0)" id="createNewuser"> 
    <i class="ri-add-line"></i>Create New user (modal)</a>



<div >
    <a style="margin: 19px;" href="{{ route('users.create')}}" class="btn btn-primary">New user (blade)</a>
</div>  



<table class="table table-striped">
    <thead>
        <tr>
        <th>ID</th>
          <th>First</th>
          <th>Last</th>
          <th>Email</th>
          <th>Phone</th>
          <th>role_id</th>
          <th colspan = 2>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach($users as $user)
        <tr>
        <td>{{ $user->id }}</td>
          <td>{{ $user->first_name }}</td>
          <td>{{ $user->last_name }}</td>
          <td>{{ $user->email }}</td>
          <td>{{ $user->phone }}</td>
          <td>{{ $user->role_id }}</td>
            <td>
                <a href="{{ route('users.edit',$user->id)}}" class="btn btn-edit">Edit</a>
            </td>
            <td>
                <form action="{{ route('users.destroy', $user->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>

  {{-- Pagination --}}
        <div class="d-flex justify-content-center">
            {!! $users->links() !!}
        </div>


<div>
</div>


<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>

@endsection