routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomAuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
| in laravel Route there is two parameters url and call back 
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/

Route::get('/', 'App\Http\Controllers\PresentationController@index');
Route::get('/about', 'App\Http\Controllers\PresentationController@about');
Route::get('/LaravelQuestions', 'App\Http\Controllers\PresentationController@LaravelQuestions');
Route::get('/LaravelDatabaseSeeding', 'App\Http\Controllers\PresentationController@LaravelDatabaseSeeding');
Route::get('/LaravelTinker', 'App\Http\Controllers\PresentationController@LaravelTinker');
Route::get('/Laraveljson', 'App\Http\Controllers\PresentationController@Laraveljson');

Route::get('/Laraveljson_import_test', 'App\Http\Controllers\jsonImportController@index');

Route::get('/blog', 'App\Http\Controllers\BlogController@index');

Route::get('/hello', function () {
    return "This is a simple Route returning hello message";
});

Route::get('users/{id}', function ($id) {
    return "Your id id $id";
});

/*
Route::get('/usershome', 'App\Http\Controllers\usersController@index')->name('usershome');
Route::get('/usercreate', 'App\Http\Controllers\usersController@create')->name('usercreate');
Route::post('/usercreate', 'App\Http\Controllers\usersController@store')->name('store');
*/
Route::resource('users', 'App\Http\Controllers\usersController');
Route::get('users', [App\Http\Controllers\usersController::class, 'getData']);

//Route::get('/companyhome', 'App\Http\Controllers\companyController@index')->name('companyhome');
//Route::resource('companyhome', 'App\Http\Controllers\companyController');
//Route::resource('customers','CustomerController');
//Route::resource('companyhome','companyController');
Route::resource('company', 'App\Http\Controllers\companyController');
Route::get('company', [App\Http\Controllers\companyController::class, 'getData']);

//Route::get('welcome', [CustomAuthController::class, 'welcome']); 
Route::get('login', [CustomAuthController::class, 'index'])->name('login');
Route::post('custom-login', [CustomAuthController::class, 'customLogin'])->name('login.custom'); 
Route::get('registration', [CustomAuthController::class, 'registration'])->name('register-user');
Route::post('custom-registration', [CustomAuthController::class, 'customRegistration'])->name('register.custom'); 
Route::get('signout', [CustomAuthController::class, 'signOut'])->name('signout');

Route::get('welcome', function () {
    return view('welcome');
});

app/Models/company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class company extends Model
{
    protected $table = 'companies';
    use HasFactory;
    public $fillable = [
        'company_name',
        'email',
        'phone'
    ];    
    public function owners()
    {
        //return $this->hasMany('App\Models\user');
    }


}

app/Http/Controllers/companyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DataTables;
use App\Models\company;  // use user model
use Illuminate\Support\Facades\DB;
Use Redirect;
use Illuminate\Support\Facades\Auth;
use Session;

class companyController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // See getData() function
        if(Auth::check()){
            $companies = company::all();
            return view('company.index', compact('companies'));
        }
  
        return redirect("welcome")->withSuccess('You are not allowed to access');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $company = new company();
        $company->company_name = $request->company_name; 
        $company->email = $request->email;
        $company->phone = $request->phone;


                $company->save();       
                
                $companies = company::all();
                return view('company.index', compact('companies'))->with('success', 'company updated!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $companies = company::paginate(5);
        return view('company.index', compact('companies'));
/*
        $company = company::find($id);
        return view('company.index', compact('company'));
        */
        }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = company::find($id);
        return view('company.edit', compact('company'));        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'company_name'=>'required',
            'email'=>'required'
        ]);

        $company = company::find($id);
        $company->company_name =  $request->company_name;
        $company->email = $request->get('email');
        //$employee->name = $request->fullname;

        $company->phone = $request->get('phone');
        $company->save();
        
        $notification = array(
            'message' => "Company (<b>" . $request->get('company_name') . "</b>) updated!",
            'alert-type' => 'success'
        );

        return redirect("company")->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        company::find($id)->delete();
        $notification = array(
            'message' => "Company deleted!",
            'alert-type' => 'success'
        );
        
        return redirect::back()->with($notification);
        //return view('company.index', compact('companies'));

    }


    public function getData()
    {
    if(Auth::check()){
        $companies = company::paginate(5);
        return view('company.index', compact('companies'));
    }

    $notification = array(
        'message' => "You are not allowed to access Company data!",
        'alert-type' => 'alert-success');

    return redirect("welcome")->with($notification);

}
 
}

resources/views/company/create.blade.php
<div class="modal-header">
                <h4 class="modal-title" id="modelHeading"></h4>
            </div>
            <div class="modal-body">
                <form id="companyForm" name="companyForm" class="form-horizontal">
                   <input type="hidden" name="company_id" id="company_id">
                    <div class="form-group">
                        <label for="company_name" class="col-sm-2 control-label">Name</label>
                        <div class="col-sm-12">
                            * <input type="text" class="form-control" id="company_name" name="company_name" placeholder="Enter Name" value="" maxlength="50" required="">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="email" name="email" placeholder="Enter email" value="" maxlength="50" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Phone</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="phone" name="phone" placeholder="Enter phone" value="" maxlength="50">
                        </div>
                    </div>

                    <div class="col-sm-offset-2 col-sm-10">
                     <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Save changes
                     </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/company/edit.blade.php
@extends('layouts.main')

@section('title', 'Edit a Company ')

@section('content')

<main id="main">
<hr>

    <!-- ======= company Section ======= -->
    <section id="company" class="company">

      <div class="container" data-aos="fade-up">

        <header class="section-header">
          <h2>Company</h2>
          <p>Listing</p>
        </header>

        <div class="container">
        


<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a company</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('company.update', $company->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="company_name">Company Name:</label>
                <input type="text" class="form-control" name="company_name" value="{{ $company->company_name }}" />
            </div>

            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" class="form-control" name="email" value="{{ $company->email }}" />
            </div>

            <div class="form-group">
                <label for="phone">Phone:</label>
                <input type="text" class="form-control" name="phone" value="{{ $company->phone }}" />
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>


</div></div></section></main>

@endsection

@section('footer-scripts')
    @include('scripts.ajax')
@endsection

resources/views/company/index.blade.php
@extends('layouts.main')

@section('title', 'Company Home')

@section('content')
 
<main id="main">

    <!-- ======= company Section ======= -->
    <section id="company" class="company">

      <div class="container" data-aos="fade-up">

        <header class="section-header">
          <h1>Companies</h1>
          <p>Listing</p>
        </header>

<div class="message" data-aos="fade-up">
@if (session('message'))
<div class="alert session('alert-type')">
{!! session('message') !!}
</div>
@endif
</div>

    <a class="btn btn-success" href="javascript:void(0)" id="createNewcompany"> 
    <i class="ri-add-line"></i>  Create New company</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th colspan = 2>Actions</th>
            </tr>
        </thead>
        <tbody>

        @foreach($companies as $company)
        <tr>
            <td>{{$company->id}}</td>
            <td>{{$company->company_name}} </td>
            <td>{{$company->email}}</td>
            <td>{{$company->phone}}</td>
            <td>
                <a href="{{ route('company.edit',$company->id)}}"
                class="btn btn-warning btn-edit">Edit  <i class="ri-pencil-line"></i> </a>
            </td>
            <td>
                <form action="{{ route('company.destroy', $company->id)}}" 
                    id="delete-form-{{ $company->id }}"
                    method="post">
                  @csrf
                  @method('DELETE')
                  <button onclick="if (confirm('Are you sure to delete this data?')) {
                    event.preventDefault();
                    document.getElementById('delete-form-{{ $company->id }}').submit();
                  }else{
                      event.preventDefault();
                  }
                    " 
                  class="btn btn-danger" type="submit">Delete <i class="ri-delete-bin-line"></i>  </button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
    </table>
    {{-- Pagination --}}
        <div class="d-flex justify-content-center">
            {!! $companies->links() !!}
        </div>

</div>

<div class="modal fade" id="ajaxModel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modelHeading"></h4>
            </div>
            <div class="modal-body">
                <form id="companyForm" name="companyForm" class="form-horizontal" 
                action="{{ route('company.store') }}" method="post">
                {{csrf_field()}}


                   <input type="hidden" name="company_id" id="company_id">
                   <div class="form-group">
                        <label for="company_name" class="col-sm-2 control-label">Name</label>
                        <div class="col-sm-12">
                            * <input type="text" class="form-control" id="company_name" name="company_name" placeholder="Enter Name" value="" maxlength="50" required="">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="email" name="email" placeholder="Enter email" value="" maxlength="50" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Phone</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="phone" name="phone" placeholder="Enter phone" value="" maxlength="50">
                        </div>
                    </div>

                    <div class="col-sm-offset-2 col-sm-10">
                     <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Save changes
                     </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



      </div>

    </section><!-- End company Section -->



</main><!-- End #main -->


@endsection

@section('footer-scripts')
    @include('scripts.ajax')
@endsection

resources/views/company/index.users.blade.php
@extends('base')

@section('main')


<div >
    <a style="margin: 19px;" href="{{ route('users.create')}}" class="btn btn-primary">New user</a>
</div>  

<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">users</h1>    
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Name</td>
          <td>Email</td>
          <td>Job Title</td>
          <td>City</td>
          <td>Country</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($users as $user)
        <tr>
            <td>{{$user->id}}</td>
            <td>{{$user->first_name}} {{$user->last_name}}</td>
            <td>{{$user->email}}</td>
            <td>{{$user->job_title}}</td>
            <td>{{$user->city}}</td>
            <td>{{$user->country}}</td>
            <td>
                <a href="{{ route('users.edit',$user->id)}}" class="btn btn-edit">Edit</a>
            </td>
            <td>
                <form action="{{ route('users.destroy', $user->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
</div>


<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>

@endsection